import { homeScreen } from './scripts_telas/1_home.js';
import { paymentsScreen } from './scripts_telas/2_sistema_de_pagamentos.js';
import { accessScreen } from './scripts_telas/3_gestao_de_acessos.js';
import { organizationsScreen } from './scripts_telas/4_gestao_de_organizacoes.js';
import { publicHomeScreen } from './scripts_telas/public_home.js';
import frontendConfig from './configuracao.json';
export const SYSTEM_NAME = String(frontendConfig.nome_sistema || 'Sistema').trim();
export const SYSTEM_EMAIL = String(frontendConfig.email_contato || '').trim().toLowerCase();
export const SYSTEM_URL = String(frontendConfig.link_sistema || '').trim();
export const PUBLIC_IMAGES_URL = `${import.meta.env.BASE_URL}imagens_pub`;
export const ORGANIZATION_IMAGES_URL = `${import.meta.env.BASE_URL}imagens`;
document.title = SYSTEM_NAME;
export const API_URL = (import.meta.env?.VITE_API_URL || 'https://logins-back.onrender.com').replace(/\/$/, '');
export const state = { token: sessionStorage.getItem('login_session') || '', session: JSON.parse(sessionStorage.getItem('login_data') || 'null') };
function escapeHtml(value) { const element = document.createElement('span'); element.textContent = String(value ?? ''); return element.innerHTML; }
export async function api(path, options = {}) { const response = await fetch(`${API_URL}${path}`, { ...options, headers: { authorization: `Bearer ${state.token}`, ...(options.body ? { 'content-type': 'application/json' } : {}), ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Nao foi possivel concluir.'); return data; }
export function logout() { sessionStorage.removeItem('login_session'); sessionStorage.removeItem('login_data'); state.token = ''; state.session = null; navigate('public'); }
export function shell(content, title) { const user = state.session.user; const role = user.role; const organization = state.session.organization; const privileged = ['admin', 'gerente'].includes(role); const owner = role === 'admin' && organization.id === 'ORG_0000'; const navigation = owner ? '<button data-page="home">Home</button><button data-page="organizations">Cadastro de Organizações</button><button data-page="payments">Sistema de Pagamento</button><button data-page="access">Gestão de Acessos</button>' : `<button data-page="home">Home</button>${privileged ? '<button data-page="payments">Sistema de Pagamento</button><button data-page="access">Gestão de Acessos</button>' : ''}`; const organizationLogo = owner ? `${PUBLIC_IMAGES_URL}/gateguard_logo.png` : `${ORGANIZATION_IMAGES_URL}/${encodeURIComponent(organization.id)}/logo.png`; return `<div class="app-shell"><header><div class="header-brand"><img data-organization-logo src="${organizationLogo}" data-fallback="${PUBLIC_IMAGES_URL}/gateguard_logo.png" alt="${escapeHtml(organization.name)}"><div><strong>${escapeHtml(SYSTEM_NAME)}</strong><small>${escapeHtml(organization.id)}</small></div></div><button id="menu-button" class="menu-button" aria-label="Abrir menu">☰</button><nav id="menu" hidden><div class="menu-user"><strong>${escapeHtml(user.name)}</strong><span><b>Perfil:</b> ${escapeHtml(role)}</span><span><b>Cargo:</b> ${escapeHtml(user.cargo || 'Não informado')}</span></div><div class="menu-links">${navigation}<button id="logout">Sair</button></div></nav></header><section class="content"><div class="title"><p>PAINEL</p><h1>${title}</h1></div>${content}</section></div>`; }
export function bindShell() { const menu = document.querySelector('#menu'); const logo = document.querySelector('[data-organization-logo]'); if (logo) logo.onerror = () => { logo.onerror = null; logo.src = logo.dataset.fallback; }; document.querySelector('#menu-button').onclick = () => { menu.hidden = !menu.hidden; }; menu.querySelectorAll('[data-page]').forEach(x => x.onclick = () => navigate(x.dataset.page)); document.querySelector('#logout').onclick = logout; }
export async function navigate(page) { const app = document.querySelector('#app'); if (!state.token || !state.session) { publicHomeScreen(app, page === 'login'); return; } if (page === 'login' || page === 'public') page = 'home'; if (page === 'payments' && !['admin', 'gerente'].includes(state.session.user.role)) page = 'home'; if (page === 'access' && !['admin', 'gerente'].includes(state.session.user.role)) page = 'home'; if (page === 'organizations' && !(state.session.user.role === 'admin' && state.session.organization.id === 'ORG_0000')) page = 'home'; if (page === 'payments') return paymentsScreen(app); if (page === 'access') return accessScreen(app); if (page === 'organizations') return organizationsScreen(app); return homeScreen(app); }
navigate(state.token ? 'home' : 'public');
