import { loginScreen } from './scripts_telas/0_login.js';
import { homeScreen } from './scripts_telas/1_home.js';
import { paymentsScreen } from './scripts_telas/2_sistema_de_pagamentos.js';
import { accessScreen } from './scripts_telas/3_gestao_de_acessos.js';
import frontendConfig from './configuracao.json';
export const SYSTEM_NAME = String(frontendConfig.nome_sistema || 'Sistema').trim();
document.title = SYSTEM_NAME;
export const API_URL = (import.meta.env?.VITE_API_URL || 'https://logins-back.onrender.com').replace(/\/$/, '');
export const state = { token: sessionStorage.getItem('login_session') || '', session: JSON.parse(sessionStorage.getItem('login_data') || 'null') };
function escapeHtml(value) { const element = document.createElement('span'); element.textContent = String(value ?? ''); return element.innerHTML; }
export async function api(path, options = {}) { const response = await fetch(`${API_URL}${path}`, { ...options, headers: { authorization: `Bearer ${state.token}`, ...(options.body ? { 'content-type': 'application/json' } : {}), ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Nao foi possivel concluir.'); return data; }
export function logout() { sessionStorage.removeItem('login_session'); sessionStorage.removeItem('login_data'); state.token = ''; state.session = null; navigate('login'); }
export function shell(content, title) { const user = state.session.user; const role = user.role; const privileged = ['admin', 'gerente'].includes(role); return `<div class="app-shell"><header><div class="header-brand"><img src="./imagens/logo.png" alt="Logo"><div><strong>${escapeHtml(SYSTEM_NAME)}</strong><small>${escapeHtml(state.session.organization.id)}</small></div></div><button id="menu-button" class="menu-button" aria-label="Abrir menu">☰</button><nav id="menu" hidden><div class="menu-user"><strong>Dados do login</strong><span><b>Nome:</b> ${escapeHtml(user.name)}</span><span><b>Perfil:</b> ${escapeHtml(role)}</span><span><b>Cargo:</b> ${escapeHtml(user.cargo || 'Não informado')}</span></div><div class="menu-links"><button data-page="home">Home</button>${privileged ? '<button data-page="payments">Sistema de Pagamento</button><button data-page="access">Gestão de Acessos</button>' : ''}<button id="logout">Sair</button></div></nav></header><section class="content"><div class="title"><p>PAINEL</p><h1>${title}</h1></div>${content}</section></div>`; }
export function bindShell() { const menu = document.querySelector('#menu'); document.querySelector('#menu-button').onclick = () => { menu.hidden = !menu.hidden; }; menu.querySelectorAll('[data-page]').forEach(x => x.onclick = () => navigate(x.dataset.page)); document.querySelector('#logout').onclick = logout; }
export async function navigate(page) { const app = document.querySelector('#app'); if (!state.token || !state.session) page = 'login'; if (page === 'login') return loginScreen(app); if (page === 'payments' && !['admin', 'gerente'].includes(state.session.user.role)) page = 'home'; if (page === 'access' && !['admin', 'gerente'].includes(state.session.user.role)) page = 'home'; if (page === 'payments') return paymentsScreen(app); if (page === 'access') return accessScreen(app); return homeScreen(app); }
navigate(state.token ? 'home' : 'login');
